apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: homelab-web-ingress
  namespace: homelab
spec:
  podSelector:
    matchLabels:
      app: homelab-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
