apiVersion: v1
kind: Service
metadata:
  name: homelab-web
  namespace: homelab
spec:
  type: NodePort
  selector:
    app: homelab-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32227
